### ISSUE TITLE
v1.0.0 tracking issue

### ISSUE THREAD

**Issue by pzuraq** [glimmerjs/glimmer.js#221]
- [x] Update the Glimmer-VM and align `@glimmer/tracking` types with Ember.js (#223)
- [x] Remove `@tracked` and `setPropertyDidUpdate` deprecations from `@glimmer/component` (#224)
- [x] Add DEBUG mode getters to Ember implementation of `@glimmer/component` to display helpful errors in case any user attempts to use things that only exist for Glimmer.js (#224)
- [x] Remove blueprints from `@glimmer/component` package, since they'll be provided by Ember and Glimmer directly (#225)
- [ ] Update the changelog with an upgrade guide for Glimmer.js users

**Comment by btecu** [comment]
Most can be checked 👍 

I would add `Making glimmer/component work in IE`: https://github.com/glimmerjs/glimmer.js/pull/227

**Comment by locks** [comment]
1.0.0 has been released.
